const NotificationTypeEnum = {
  CENSOR_ROOM_POSTED: "CENSOR_ROOM_POSTED",
  NEW_TRANSACTION: "NEW_TRANSACTION",
  CENSORSHIP_SUCCESSFUL: "CENSORSHIP_SUCCESSFUL",
  CENSORSHIP_FAILED: "CENSORSHIP_FAILED",
  UP_MEMBERSHIP: "UP_MEMBERSHIP",
  PAYMENT_SUCCESSFUL: "PAYMENT_SUCCESSFUL",
  PAYMENT_FAILED: "PAYMENT_FAILED",
};

module.exports = NotificationTypeEnum;
